version: "3"
services:
  mongo:
    image: mongo:3.4-jessie
    command: mongod --port 47017
    volumes:
      - ".volumes/mongo:/data/db:Z"
  consul:
    image: consul
    environment:
     - "CONSUL_BIND_INTERFACE=eth0"
    links:
      - mongo
    ports:
      - 8500:8500
  app:
    build: .
    image: app
    environment:
      - NODE_ENV=prod
      - MONGO_HOST=mongodb://mongo:47017/frirso
      - LOGZIO_TOKEN=eca47bff-b428-4f3a-bb96-06d77ec121c0
      - CONSUL_HOST=consul
    ports:
      - 80:3000
    depends_on:
      - mongo
      - consul
